sudo: false

language: php

notifications:
  email: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=trunk
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest

install:
  - |
    wget https://github.com/runkit7/runkit7/releases/download/1.0.5b1/runkit-1.0.5b1.tgz &&
    pecl install runkit-1.0.5b1.tgz
  - composer install --prefer-dist --no-scripts
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

before_script:
  - ./vendor/bin/wp-enforcer

script:
  - WP_MULTISITE=0 phpunit
  - WP_MULTISITE=1 phpunit
  - ./vendor/bin/phpcs --standard=phpcs.xml ./
