sudo: false

language: php

notifications:
  email: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest

    # Test against the trunk version of core.
    - php: 5.6
      env: WP_VERSION=trunk

    # Run against the minimum-supported WordPress version, per readme.txt.
    - php: 5.6
      env: WP_VERSION=3.2

    # Run against the minimum-supported PHP version.
    - php: 5.3
      env: WP_VERSION=latest

install:
  - composer-install --prefer-source
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then
        composer global require "phpunit/phpunit=4.8.*"
      else
        composer global require "phpunit/phpunit=5.7.*"
      fi
    fi

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      wp-enforcer
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      echo -e "\033[0;32mRunning tests as WordPress multisite:\033[0m"
      WP_MULTISITE=1 phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs --standard=phpcs.xml
    fi
